app = "camelitesminimart"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
SPRING_PROFILES_ACTIVE = "prod"
[build]
  builder = "paketobuildpacks/builder:base"

[experimental]
  auto_rollback = true 

[[services]]
internal_port = 8080
external_port = 80
protocol = "tcp"
