app = "camelitesminimart"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
SPRING_PROFILES_ACTIVE = "prod"

[[services]]
internal_port = 8080
protocol = "tcp"

  [services.ports]
  http = 80
  https = 443