app = "camelitesminimart"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
SPRING_PROFILES_ACTIVE = "prod"
PORT="8080"
SERVER_ADDRESS="0.0.0.0"
[build]
  builder = "paketobuildpacks/builder:base"
  command = "java -jar your-app.jar"

[experimental]
  auto_rollback = true 


[[services]]
internal_port = 8080
external_port = 80
protocol = "tcp"


