app = "camelitesminimart"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  SPRING_PROFILES_ACTIVE = "prod"
  PORT = "8080" # Fly.io sets the port dynamically but defaults to 8080
  DATABASE_URL = "jdbc:postgresql://your-production-db-url"
  DB_USERNAME = "your_prod_username"
  DB_PASSWORD = "your_prod_password"

[build]
  builder = "paketobuildpacks/builder:base"

[deploy]
  strategy = "rolling"